---
- name: My Test Playbook
  hosts: all
  become: yes

  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Starting httpd
    service:
      name: http----
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: Installing apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags:
    - ubuntu

  - name: Starting apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags:
    - ubuntu

  - name: Copy index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666
